### ISSUE TITLE
Missing nickname isn't handled properly when adding a signup manually

### ISSUE THREAD

**Issue by Gehock** [zeusops/operationbot#32]
> [23:56] Stroker: !signup 208 "Irish" Zeus
> [23:56] B. Event: User None signed up to event Operation at 2020-05-16 18:45:00 as Zeus

**Comment by MaxKosi** [comment]
![image](https://user-images.githubusercontent.com/81243594/112448607-db3d6280-8d52-11eb-911d-87ef0cc1c05a.png)

**Comment by Gehock** [comment]
The issue here was that Irish didn't have a Guild-specific nickname set. So the bot should use `Member.display_name` (which automatically returns the nickname if that exists and otherwise returns the username) instead of `Member.nick` when showing user data

**Comment by MaxKosi** [comment]
https://github.com/zeusops/operationbot/blob/250579f3c78d5453a45d365b1e22beb30b71052d/commandListener.py#L721

Can you confirm that this Issue still exists?

**Comment by Gehock** [comment]
This seems to have disappeared at some point, wasn't able to reproduce anymore.
