### ISSUE TITLE
Should not ping the event moderator for their own sign-off

### ISSUE THREAD

**Issue by Gehock** [zeusops/operationbot#36]
> [12:34] B. Event: @ Moderator: User Moderator (Moderator#1337) signed off from Operation at 2020-07-24 18:45:00 role :ESL: 7 hours 10 minutes before the operation.

**Comment by MaxKosi** [comment]
check Branch Issue#36
Its not tested
eventListener.py line 153

**Comment by Gehock** [comment]
Tip: you can refer to specific points at files by copying the direct link to a line in a commit: 

https://github.com/zeusops/operationbot/blob/5eba648899306a700541a138b262a39d7243863f/eventListener.py#L152-L153

**Comment by MaxKosi** [comment]
uhhhh new stuff
