### ISSUE TITLE
A priority command

### ISSUE THREAD

**Issue by Gehock** [zeusops/operationbot#37]
> [13:35] Stroker: A priority bot would be cool, so I do a command and it wipes anything that the person previously signed up for (e.g. if they were B1 and took priority on BSL, it unsigned them from B1 and overrides BSL) and then outputs it in #arma

Related to #20

**Comment by MaxKosi** [comment]
doesnt this already exist? except the output in arma

**Comment by Gehock** [comment]
Yeah, the functionality for replacing a signup does already exist, the only required addition would be to inform the user(s) in `#arma`. Preferably this should be a separate command, there are cases where we want to replace the signup without pinging people unnecessarily (zeuses changing dates, for example)

**Comment by MaxKosi** [comment]
having a seperate command that the moderator needs to run seems kinda pointless to me. He could ping him instead with the same result.
We could automate a function that pings  everyone who signed up for that event a few hours before that event happens

**Comment by Gehock** [comment]
What I meant is we'd have two commands:
- `!signup` (already exists) which removes the old signup and replaces that with a new one
- `!priority` which does everything that `!signup` does but additionally also pings the affected players

**Comment by Gehock** [comment]
> We could automate a function that pings everyone who signed up for that event a few hours before that event happens

This could be very useful as well, but not relevant to this issue

**Comment by MaxKosi** [comment]
Couldnt we just modify this case? Or is there a case where this happens and its not priority?

https://github.com/zeusops/operationbot/blob/edf58f9f025f220548ba63a554bb0b5a96def064/commandListener.py#L724-L726

**Comment by Gehock** [comment]
I'll have to confirm with Stroker but I think I remember her saying she wants to explicitly know when the command would ping somebody

**Comment by Gehock** [comment]
Replacing a sign-up works already, don't see the need to automatically output in #arma.
