### ISSUE TITLE
Mentions for late sign-offs do not work

### ISSUE THREAD

**Issue by Gehock** [zeusops/operationbot#43]
Seems to have broken some time late 2020.

Blocks #36 
Blocks #57

**Comment by MaxKosi** [comment]
https://discordpy.readthedocs.io/en/latest/intents.html

Since an update the bot needs a configured intent. Without that it is not able to see the members.
I have set the intent to all() (all permissions) and it is able to see the members. It might need some tinkering, but works like that

Check branch Issue#43
main.py line 14

**Comment by Gehock** [comment]
Oh, that's actually quite interesting. I vaguely remember getting a notification about the Discord gateway change regarding Intents some time last summer but had completely forgotten that I hadn't already implemented the changes. Now I'm slightly surprised that the bot has worked at all until this point.

> I have set the intent to all() (all permissions) and it is able to see the members. It might need some tinkering, but works like that

It seems to me that the default intent + members should be enough for now, we don't currently need the information about user presences.

> PS: Branch Issue#43 contains content of Issue#46 - I just noticed that

You might have to do some rebasing when the displayName branch updates but that's not an issue otherwise

**Comment by MaxKosi** [comment]
All of the above is done.
If you want to you can send it to the master, but I want to finish pull_request #46 first

**Comment by Gehock** [comment]
Feel free to create a draft pull request, makes it easier to review the changes

**Comment by HPApples** [comment]
So this is still broke? did intent fix?

**Comment by MaxKosi** [comment]
it fixes it. all that it needs is to be merged to master branch. I wanted to merge #47  first though

**Comment by HPApples** [comment]
Lovely, the issues page is going to look nice once the branch is merged. I think we have solved like 6-7 issues in the last couple days :POG:
