### ISSUE TITLE
Make the time zone configurable

### ISSUE THREAD

**Issue by Gehock** [zeusops/operationbot#50]
Related to #49 

Currently the time zone is hard-coded in `event.py`: https://github.com/zeusops/operationbot/blob/b1fec15c1fefb4d43ba7050d3ea6c3dd42d4348d/event.py#L213

Preferably it should be somehow configurable trough `config.py`

**Comment by HPApples** [comment]
TODO when im home: 

Add , cfg.TIME_ZONE to line 213 event.py
Add TIME_ZONE = "CET" to config.py

**Comment by MaxKosi** [comment]
#71 isn't this the same?
Being related to #49 is correct though

**Comment by Gehock** [comment]
Fixed in 758f5c6748da39f79d5dceb185b053d67d29eee0
